service: todont
image: binny0/todont

servers:
  web:
    hosts:
      - 49.13.90.233
    labels:
      traefik.http.routers.todont.rule: Host(`todont.duckdns.org`)
      traefik.http.services.todont.loadbalancer.server.port: "3000"
    env:
      BINDING: 0.0.0.0

registry:
  server: registry.hub.docker.com
  username: binny0
  password: <%= ENV.fetch("KAMAL_REGISTRY_PASSWORD") %>

proxy:
  app_port: 3000

builder:
  arch: 
    - amd64
  local: true
  # remote: true

env:
  RAILS_MASTER_KEY: <%= ENV.fetch("RAILS_MASTER_KEY") %>
  # Use the full container name
  DATABASE_URL: postgresql://postgres:postgres@todont-postgres:5432/todont_production
  # Use the full container name
  REDIS_URL: redis://todont-redis:6379/1
  KAMAL_PROXY_IP: "true"

volumes:
  - "/var/lib/postgresql/data:/var/lib/postgresql/data"
  - "/var/lib/redis:/var/lib/redis"
  - "/rails/storage:/rails/storage"
 